#!/usr/bin/env bash

actual_checksum=$(curl http://fp-cli.org/packages/phar/fp-cli.phar | md5sum | cut -d ' ' -f 1)

echo "expected:" $(curl -s http://fp-cli.org/packages/phar/fp-cli.phar.md5)
echo "actual:  " $actual_checksum

actual_checksum=$(curl http://fp-cli.org/packages/phar/fp-cli.phar | sha512sum | cut -d ' ' -f 1)

echo "expected SHA-512:" $(curl -s http://fp-cli.org/packages/phar/fp-cli.phar.sha512)
echo "actual SHA-512:  " $actual_checksum
